<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="LOG_ORCHESTRATOR_PRODUCT_AD_ADAPTER" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/O2/O2/LOG_ORCHESTRATOR_PRODUCT_AD_ADAPTER" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/O2/O2/LOG_ORCHESTRATOR_PRODUCT_AD_ADAPTER" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/LOG_ORCHESTRATOR_PRODUCT_AD_ADAPTER">
   <plt:partnerLinkType name="LOG_ORCHESTRATOR_PRODUCT_AD_ADAPTER_plt">
      <plt:role name="LOG_ORCHESTRATOR_PRODUCT_AD_ADAPTER_role">
         <plt:portType name="tns:LOG_ORCHESTRATOR_PRODUCT_AD_ADAPTER_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/LOG_ORCHESTRATOR_PRODUCT_AD_ADAPTER" schemaLocation="xsd/LOG_ORCHESTRATOR_PRODUCT_AD_ADAPTER_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="LogOrchestratorProductAdCollection_msg">
      <wsdl:part name="LogOrchestratorProductAdCollection" element="top:LogOrchestratorProductAdCollection"/>
   </wsdl:message>
   <wsdl:portType name="LOG_ORCHESTRATOR_PRODUCT_AD_ADAPTER_ptt">
      <wsdl:operation name="insert">
         <wsdl:input message="tns:LogOrchestratorProductAdCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
