<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="OrderInterpreterProcess" targetNamespace="http://tigo.com/enterprise/business/task/OrderBroker/v1/OrderInterpreterProcess" xmlns:ns2="http://xmlns.tigo.com/ProcessValidator/ValidateRequest" xmlns:ns1="http://tigo.com/enterprise/serviceEntity/provisioning/orderRequest/v1/schema" xmlns:ns4="http://xmlns.tigo.com/ProcessValidator/ValidateRequest/v3" xmlns:ns3="http://tigo.com/enterprise/business/task/OrderBroker/v1/PVSProcess" xmlns:tns="http://tigo.com/enterprise/business/task/OrderBroker/v1/OrderInterpreterProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:sch="http://tigo.com/enterprise/business/task/OrderBroker/v1/schema" xmlns:grs="http://tigo.com/enterprise/resources/GeneralResponse/v1/schema">
   <wsdl:types>
      <xsd:schema xmlns:ns2="http://xmlns.tigo.com/ProcessValidator/ValidateRequest" xmlns:ns1="http://tigo.com/enterprise/serviceEntity/provisioning/orderRequest/v1/schema" xmlns:ns3="http://tigo.com/enterprise/business/task/OrderBroker/v1/PVSProcess" xmlns:tns="http://tigo.com/enterprise/business/task/OrderBroker/v1/OrderInterpreterProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:sch="http://tigo.com/enterprise/business/task/OrderBroker/v1/schema" xmlns:grs="http://tigo.com/enterprise/resources/GeneralResponse/v1/schema" xmlns:ns4="http://xmlns.tigo.com/ProcessValidator/ValidateRequest/v3">
         <xsd:import namespace="http://tigo.com/enterprise/business/task/OrderBroker/v1/schema" schemaLocation="../../xsd/owner/OrderBroker_schema.xsd"/>
         <xsd:import namespace="http://tigo.com/enterprise/resources/GeneralResponse/v1/schema" schemaLocation="../../xsd/commons/resources/GeneralResponse.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="SubmitOrderRequest_msg">
      <wsdl:part name="body" element="sch:SubmitOrder_Request"/>
   </wsdl:message>
   <wsdl:message name="SubmitOrderResponse_msg">
      <wsdl:part name="body" element="sch:SubmitOrder_Response"/>
   </wsdl:message>
   <wsdl:message name="GeneralResponseMessage">
      <wsdl:part name="fault" element="grs:GeneralResponse"/>
   </wsdl:message>
   <wsdl:portType name="OrderInterpreterProcessPortType">
      <wsdl:operation name="SubmitOrder">
         <wsdl:input name="SubmitOrder_RequestPort" message="tns:SubmitOrderRequest_msg"/>
         <wsdl:output name="SubmitOrder_ResponsePort" message="tns:SubmitOrderResponse_msg"/>
         <wsdl:fault name="fault" message="tns:GeneralResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="OrderInterpreterProcess_SOAP" type="tns:OrderInterpreterProcessPortType">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="SubmitOrder">
         <soap:operation soapAction="" soapActionRequired="false"/>
         <wsdl:input name="SubmitOrder_RequestPort">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="SubmitOrder_ResponsePort">
            <soap:body use="literal"/>
         </wsdl:output>
         <wsdl:fault name="fault">
            <soap:fault name="fault" use="literal"/>
         </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>
</wsdl:definitions>
